<!DOCTYPE html>
<html>

    <head lang="en">
        <link rel="stylesheet" type="text/html" href="css/common.css">
        <link rel="stylesheet" type="text/html" href="css/slider.css">
        <script src="js/jquery-1.11.3.min.js"></script>
        <script src="js/common.js"></script>
        <script src="js/jquery.mask.min.js"></script>
        <script src="js/slider.js"></script>
        <meta charset="UTF-8">
        <title>Kote-Georgia</title>
    </head>

 <body>

  <header>
    <div id="centeredHeader">
      <img id="logo" src="img/logo.png" />

      <div id="headerText">
        <span class="left_header_text">Автобусные туры</span>
        <span class="left_header_text">в Грузию из Украины</span>
      </div>

      <div class="phoneBox">
        <span class="phone">+380 97 815 68 38</span>
        <span class="phone">+380 50 774 99 18</span>
        <span class="phone">+380 63 796 25 00</span>
      </div>
    </div>
  </header>

  <div id="block1">
      <div id="firstBlock_centered" class="centeredBlock">
          <h1>
              Прямые автобусные туры в <br/> Грузию из Украины
          </h1>

          <div id="tourInfo">
              <span id="firstText" class="tourText">Отдыхай в Грузии за <span class="tourNumbers">39$</span></span>
              <span id="secondText" class="tourText">Более <span class="tourNumbers">30</span> гарантированных выездов этим летом</span>
              <span id="lastText"  class="tourText">В <span class="tourNumbers">5</span> раз дешевле авиабилета</span>
          </div>

          <div class="application">
              <h2 class="application_h2">Оставьте заявку</h2>
              <span class="app_about">на тур в Грузию</span><br/>
              <span class="app_about">и получите скидку на проживание</span>

              <form id="form" action="mail.php" method="post">
                <input class="app_input" type="text" placeholder="Ваше имя" name="clientName" />
                <input class="app_input last form_phone" type="text" placeholder="Ваш телефон" name="clientPhone" />
                <input class="app_btn" type="submit" value="" />
              </form>

              <p class="secureBox">
                <img class="lock" src="img/secured.png" />
                <span class="personalInfo">Ваши данные в безопасности</span>
                <span class="personalInfo">И не будут переданы третьим лицам</span>
              </p>
          </div>
      </div>
  </div>

  <div id="block2">
      <div class="centeredBlock align_center">
          <img class="rocks" src="img/rocs.png" />

          <div id="we_r_block">
            <span id="why"> Почему </span>
            <span id="we_r_best"> мы лучшие? </span>
            <hr />
          </div>

          <div id="block2_reasons">

            <div class="Line_plane first">
                <img src="img/bus.png" /><br/>
                <span class="plane_text">Проезд на автобусах</span><br/>
                <span class="plane_text">люкс класса</span><br/>
                <span class="plane_text">&nbsp;</span>
            </div>

            <div class="Line_plane">
               <img src="img/plane.png" /><br/>
               <span class="plane_text">В 3 раза дешевле</span><br/>
               <span class="plane_text">авиатура</span><br/>
               <span class="plane_text">&nbsp;</span>
            </div>

            <div class="Line_plane last">
               <img src="img/hotel.png" /><br/>
               <span class="plane_text">42 варианта</span><br/>
               <span class="plane_text">проживания в</span><br/>
               <span class="plane_text">Тбилиси,Батуми</span>
            </div><br/>

            <div class="Line_plane first second_line">
               <img src="img/case.png" /><br/>
               <span class="plane_text">30 выездов </span><br/>
               <span class="plane_text">на лето 2015</span>
            </div>

            <div class="Line_plane second_line">
               <img src="img/guys.png" /><br/>
               <span class="plane_text">1 тыс. туристов</span><br/>
               <span class="plane_text">каждый год</span>
            </div>

            <div class="Line_plane second_line last">
               <img src="img/map.png" /><br/>
               <span class="plane_text">2 офиса КОТЕ в</span><br/>
               <span class="plane_text">Батуми и Тбилиси</span>
            </div>

          </div>

      </div>
  </div>

<div id="block3">
    <div class="centeredBlock align_center">
        <div id="service_block">
            <span id="services"> Наши услуги </span>
            <hr/>
        </div>

        <div id="tours">
            <div class="tour_block">
                <div class="head_tour">
                    <div class="head_title">Размещение 2*
                    </div>
                    <div class="helper"></div>
                </div>

                <div class="price_head">
                    265<span class="usd"> usd</span>
                </div>

                <div class="block_text">
                    — Тбилиси: bavly hostel (1 ночь)<br/><br/>
                    — Батуми: гостиница G-bakuri 2*<br/>
                    (4 ночи)<br/><br/>
                    — Гудаури: 3-4 местные номера<br/>
                    (1 ночь)<br/><br/>
                    <hr/>
                </div>
                    <a href="#application"><input type="button" class="tour_btn"/></a>
            </div>
            <div class="tour_block">
                <div class="head_tour">
                    <div class="head_title">Размещение 2*<br/>
                        11 ночей Батуми
                    </div>
                    <div class="helper"></div>
                </div>

                <div class="price_head">
                    455<span class="usd"> usd</span>
                </div>

                <div class="block_text">
                    — Тбилиси: bavly hostel (1 ночь)<br/><br/>
                    — Батуми: гостиница G-bakuri 2*<br/>
                    (11 ночей)<br/><br/>
                    — Гудаури: 3-4 местные номера<br/>
                    (1 ночь)<br/><br/>
                    <hr/>
                </div>
                <a href="#application" >
                    <input type="button" class="tour_btn"/>
                </a>
            </div>
            <div class="tour_block">
                <div class="head_tour">
                    <div class="head_title">Размещение 3*<br/>
                        11 ночей Батуми
                    </div>
                    <div class="helper"></div>
                </div>

                <div class="price_head">
                    315<span class="usd"> usd</span>
                </div>

                <div class="block_text">
                    — Тбилиси:  гостиница<br/>
                    Александрия (1 ночь)<br/><br/>
                    — Батуми:  гостиница Дельфин<br/>
                    3* (4 ночи)<br/><br/>
                    — Гудаури: 2х местные номера<br/>
                    (1 ночь)<br/>
                    <hr/>
                </div>
                <a href="#application"><input type="button" class="tour_btn"/></a>
            </div>
            <div class="tour_block">
                <div class="head_tour">
                    <div class="head_title">Размещение 3*<br/>
                        11 ночей Батуми
                    </div>
                    <div class="helper"></div>
                </div>

                <div class="price_head">
                    555<span class="usd"> usd</span>
                </div>

                <div class="block_text">
                    — Тбилиси:  гостиница<br/>
                    Александрия (1 ночь)<br/><br/>
                    — Батуми:  гостиница Дельфин<br/>
                    3* (11 ночей)<br/><br/>
                    — Гудаури: 2х местные номера<br/>
                    (1 ночь)<br/>
                    <hr/>
                </div>
                <a href="#application"><input type="button" class="tour_btn"/></a>
            </div>
        </div>
    </div>
</div>



<div id="block4">
    <div class="centeredBlock align_center">

        <div id="photo_block">
            <span id="photo_"> Фото </span>
            <span id="photo_tourists"> Наших туристов </span>
            <hr/>
        </div>

        <a  class="control_prev"><img src="img/arrow-slider.png" /></a>
        <div id="slider">
            <!--<a href="#" class="control_next"><img src="img/arrow-slider.png" /></a>-->
            <!--<a href="#" class="control_prev"><img src="img/arrow-slider.png" /></a>-->
            <ul>
                <li class="slidingImage1"><img src="img/slider1.png" /></li>
                <li class="slidingImage1"><img src="img/slider2.png" /></li>
                <li class="slidingImage1"><img src="img/slider3.png" /></li>
                <li class="slidingImage1"><img src="img/slider4.png" /></li>
                <li class="slidingImage1"><img src="img/slider5.png" /></li>
                <li class="slidingImage1"><img src="img/slider6.png" /></li>
                <!--<li class="slidingImage1"><img src="img/slider7.png" /></li>-->
                <li class="slidingImage1"><img src="img/slider8.png" /></li>
            </ul>

        </div>

        <a  class="control_next"><img src="img/arrow-slider.png" /></a>
    </div>
</div>


  <div id="block5">
      <div class="centeredBlock align_center">

          <div id="answersBlock">
              <span id="answers"> Ответы </span>
              <span id="question"> На часто задаваемые вопросы </span>
              <hr />
          </div>

          <div id="question_answer">

            <div class="currentAnswer">
               <div class="question_Block opened">
                  <span class="question_">1. Зачем в Грузию ехать на автобусе? Ведь можно полететь!</span>
                  <img class="arrow" src="img/arrow-top.png" />
               </div>
               <div id="visibleAnswer" class="answer_">
                  Да, действительно можно купить авиабилет и через пару часов оказаться в Тбилиси либо Батуми.
                  Но здесь возникнет вопрос цены!
                  Стоимость авиабилетов составляет от 200$ + проживание + трансферы + экскурсии +…= 500+$ как минимум.
                  За счет массовости и экономии на аренде транспорта в самой Грузии мы предлагаем уникальную цену и маршрут
                  для того чтобы Вы увидели Грузию по максимуму!
               </div>
            </div>

            <div class="currentAnswer">
               <div class="question_Block">
                  <span class="question_">2. На автобусе в Грузию ехать долго?</span>
                  <img class="arrow" src="img/arrow-bottom.png" />
               </div>
               <div class="answer_">
                 Так как переезд из Украины в Грузию занимает около 30и часов —  то
                   наша компания уделяет особое внимание уровню комфорта в пути.
                 Наши туры обслуживают исключительно специально подготовленные автобусы и экипажи водителей.
                 Кофеварка, розетки, wi-fi, мягкий салон, климат-контроль, аудио-видео система, профессиональные гиды  —
                 все это делает дорогу в Грузию приятным путешествием!
                </div>
            </div>

            <div class="currentAnswer">
                <div class="question_Block">
                    <span class="question_">3. Какие гарантии?</span>
                    <img class="arrow" src="img/arrow-bottom.png" />
                </div>
                <div class="answer_">
                    Туристический оператор «КОТЕ» работает на рынке Украины с 2010 года.
                    КОТЕ — лицензированный международный оператор.
                    При оформлении тура мы подписываем договор, выдаем полный пакет документов.
                </div>
            </div>

            <div class="currentAnswer">
                <div class="question_Block">
                    <span class="question_">4. Кто сопровождает группу в Грузию? И к кому общаться в самой Грузии?</span>
                    <img class="arrow" src="img/arrow-bottom.png" />
                </div>
                <div class="answer_">
                    «КОТЕ» — профильный туроператор по Грузии. Мы знаем насколько важен хороший гид в туре —
                    ведь от этого зависит ваши впечатления об отдыхе и наша репутация.
                    Наши туры сопровождают молодые, энергичные гиды, которые уже имеют немалый опыт сопровождения и
                    всегда внимательно отнесутся к вашим вопросам и предложениям в любое время суток.
                    В самой Грузии в летний сезон  «КОТЕ» открывает офис в Батуми для удобства туристов и улучшения нашего сервиса в Грузии.
                </div>
            </div>

            <div class="currentAnswer">
                <div class="question_Block">
                    <span class="question_">5. Что если не получилось поехать, а тур уже оплатили?</span>
                    <img class="arrow" src="img/arrow-bottom.png" />
                </div>
                <div class="answer_">
                    Наша компания с пониманием относиться к жизненным обстоятельствам каждого туриста,
                    и мы всегда готовы пойти навстречу и перенести оплату в полном размере на другую дату.
                    Обратите внимание на количество гарантированных выездов каждый месяц!
                </div>
            </div>

          </div>

      </div>
  </div>

  <div id="block6">
      <div class="centeredBlock align_center">
        <img class="rocks" src="img/rocs.png" />

          <div id="callBackBox">
              <span id="callbacks"> Отзывы </span>
              <span id="clientCallback"> Наших Клиентов </span>
              <hr />
          </div>

          <div class="Callback">
            <img class="leftImg" src="img/girl1.png" />

            <div class="tourist_info left">
                <span class="tourist_name"> Анна Коваленко </span><br/>
                <span class="city"> Одесса </span><br/>
                <span class="age"> 23 года </span><br/>

                <div class="about_tour">
                    "Мечтала отдохнуть в Грузии, но не было компании.
                    В «КОТЕ» меня убедили, что скучно не будет, и я решилась поехать одна.
                    И очень этому рада, так как кроме всех ярких впечатлений от поездки, я привезла кое-что еще…
                    Уезжала я одна, а вернулась с новыми друзьями и молодым человеком!
                    Теперь путешествуем вместе и скоро свадьба в Грузии! Спасибо «КОТЕ»!"
                </div>
            </div>
              <hr/>
          </div>

          <div class="Callback">
              <img class="rightImg" src="img/girl2.png" />

              <div class="tourist_info">
                  <span class="tourist_name"> Людмила Моисеева </span><br/>
                  <span class="city"> Белая Церковь </span><br/>
                  <span class="age"> 55 лет </span><br/>

                  <div class="about_tour">
                      "Забронировала место в автобусном туре в Грузию, но очень переживала по поводу дороги.
                      Не выношу долгих переездов (проблемы со спиной). Но автобус оказался очень комфортным:
                      ночью выспались лежа (сидения полностью разложили), днем – наслаждались видами из окна и занимательными рассказами гидов.
                      Ехать было мягко и удобно даже на украинских дорогах."
                  </div>
              </div>
                <hr/>
          </div>

          <div class="Callback">
              <img class="leftImg" src="img/boy.png" />

              <div class="tourist_info left">
                  <span class="tourist_name"> Владимир Масийчук </span><br/>
                  <span class="city"> Харьков </span><br/>
                  <span class="age"> 25 лет </span><br/>

                  <div class="about_tour">
                      "Очень хотелось не просто увидеть Грузию, хотелось в нее погрузиться.
                      И автобусный тур, как оказалось, подошел для этого просто идеально.
                      Долго сомневался, что лучше потратить: время на дорогу или деньги на перелет.
                      И все-таки сделал правильный выбор! Дорога стала для меня неотъемлемой частью путешествия,
                      к тому же удалось сэкономить на авиа (автобусом почти вполовину дешевле и в 2 раза интереснее!)"
                  </div>
              </div>
          </div>

      </div>
  </div>
 <div id="block7">
     <div class="centeredBlock">
         <h1 class="footer_H1">
             Прямые автобусные туры в <br/> Грузию из Украины
         </h1>
         <div class="footerInfo">
             <div class="questions">Если у Вас остались вопросы — <span class="black-font">обратитесь</span> к нашему<br/>
                 консультанту
             </div>
             <div class="question_phones">
                 <span class="question_phone">+ 380 <span class="bold_phone">97 815 68 38</span></span>
                 <span class="question_phone">+ 380 <span class="bold_phone">50 774 99 18</span></span>
                 <span class="question_phone">+ 380 <span class="bold_phone">63 796 25 00</span></span>
             </div>
             <div class="red_strip">
                 ИЛИ ОСТАВЬТЕ ЗАЯВКУ И МЫ ВАМ ПЕРЕЗВОНИМ
                 <div class="helper"></div>
             </div>
         </div>

         <div class="application" id="application">
             <h2 class="application_h2">Оставьте заявку</h2>
             <span class="app_about">на тур в Грузию</span><br/>
             <span class="app_about">и получите скидку на проживание</span>

             <form id="" action="" type="post">
                 <input class="app_input" id="name-input" type="text" placeholder="Ваше имя" name="clientName" />
                 <input class="app_input last form_phone" type="text" placeholder="Ваш телефон" name="clientPhone" />
                 <input class="app_btn" type="submit" value="" />
             </form>

             <p class="secureBox">
                 <img class="lock" src="img/secured.png" />
                 <span class="personalInfo">Ваши данные в безопасности</span>
                 <span class="personalInfo">И не будут переданы третьим лицам</span>
             </p>
         </div>
     </div>
 </div>
 <footer>
     <div class="copyright">
         © 2015 all rights reserved<br/>
         bustogeorgia.in.ua
     </div>
     <div class="helper"></div>
     <!— Yandex.Metrika informer —>
     <a style="display: none" href="https://metrika.yandex.ua/stat/?id=30238469&amp;f.."
        target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/30238469/3_1_FFFFFFFF_EFEFEFFF_.."
                                            style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: дані за сьогодні (перегляди, візити та унікальні відвідувачі)" onclick="try{Ya.Metrika.informer({i:this,id:30238469,lang:'ua'});return false}catch(e){}" /></a>
     <!— /Yandex.Metrika informer —>

     <!— Yandex.Metrika counter —>
     <script type="text/javascript">
         (function (d, w, c) {
             (w[c] = w[c] || []).push(function() {
                 try {
                     w.yaCounter30238469 = new Ya.Metrika({
                         id:30238469,
                         clickmap:true,
                         trackLinks:true,
                         accurateTrackBounce:true,
                         webvisor:true,
                         trackHash:true
                     });
                 } catch(e) { }
             });

             var n = d.getElementsByTagName("script")[0],
                 s = d.createElement("script"),
                 f = function () { n.parentNode.insertBefore(s, n); };
             s.type = "text/javascript";
             s.async = true;
             s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

             if (w.opera == "[object Opera]") {
                 d.addEventListener("DOMContentLoaded", f, false);
             } else { f(); }
         })(document, window, "yandex_metrika_callbacks");
     </script>
     <noscript><div><img src="//mc.yandex.ru/watch/30238469" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
     <!— /Yandex.Metrika counter —>
     <div id="fix_helper" class="helper"></div>
 </footer>
 </body>
</html>